version: '3.2'
volumes:
  data-db:
    driver: "local"

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - 'data-db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
